<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>2_准备_回调函数的分类</title>
</head>
<body>
<script>
    // 进一步理解]S中的错误(Error)和错误处理
    // mdn:https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Error
    // 1.错误的类型
    // Error:所有错误的父类型
    // ReferenceError:引用的变量不存在 a is not defined console.log(a)
    // TypeError:数据类型不正确 const demo =()=>{} demo()()
    // RangeError:数据值不在其所允许的范围内 const demo =()=>{demo()} demo()
    // SyntaxError:语法错误 console.log(1
    // 2.错误处理
    // 捕获错误：try{}catch()]
    // 抛出错误：throw error
    // 3.错误对象
    // message属性：错误相关信息
    // stack属件：记录信息

    //如何捕获一个错误
    /*
    1.try中放可能出现错误的代码，一旦出现错误立即停止try中代码的执行，调用catch,并携带错误信息
    */
    try{
        console.log(1);
        console.log(a);
        console.log(2);
    }catch (error){
    console.log(error)
    }
    // 如何抛出一个错误
    function demo(){
        const date = Date.now()
        if(date % 2 === 0){
            console.log('偶数')
        }else{
            throw new Error('奇数')
        }
    }
    try {
        demo()
    }catch (e) {
        debugger;
    }

</script>
</body>
</html>